[package]
name = "mochi-extractors"
version = "0.0.1"
edition = "2021"

[dependencies]
mochi-imports = { version = "0.0.1", path = "../imports" }
mochi-structs = { version = "0.0.1", path = "../structs" }